version: "3"
services:
  frontend-service:
    volumes:
      - "/app/node_modules"
      - "./src:/app/src"
      - "./public:/app/public"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000